status = error

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} \
  %highlight{%-5level}{FATAL=red,ERROR=red,WARN=yellow,INFO=green,DEBUG=faint,TRACE=white} \
  --- [%15.15t] \
  %highlight{%-40.40c{1.}}{FATAL=red,ERROR=red,WARN=yellow,INFO=green,DEBUG=faint,TRACE=white} \
  : %m%n



rootLogger.level = debug
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = STDOUT
